/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-background": "#121c2a",
        "primary-fixed": "#d2e4ff",
        "inverse-primary": "#a0c9ff",
        "outline-variant": "#c2c7d1",
        "surface-variant": "#d9e3f6",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d0dbed",
        "primary-container": "#0f4c81",
        "surface-container": "#e6eeff",
        "error": "#ba1a1a",
        "secondary": "#006c49",
        "surface-tint": "#2d6197",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#410006",
        "on-error": "#ffffff",
        "inverse-surface": "#27313f",
        "surface-container-highest": "#d9e3f6",
        "on-tertiary-container": "#ffa09d",
        "on-primary-container": "#8ebdf9",
        "inverse-on-surface": "#eaf1ff",
        "primary": "#00355f",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dee9fc",
        "on-surface-variant": "#42474f",
        "surface": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#8c2127",
        "tertiary": "#6c0513",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#07497d",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed": "#ffdad8",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "primary-fixed-dim": "#a0c9ff",
        "tertiary-fixed-dim": "#ffb3b0",
        "secondary-container": "#6cf8bb",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#121c2a",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#881d24",
        "on-primary-fixed": "#001c37",
        "on-secondary-container": "#00714d",
        "outline": "#727780",
        "on-secondary-fixed": "#002113"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "lg": "24px",
        "max-width": "1280px",
        "xl": "32px",
        "sm": "8px",
        "gutter": "24px",
        "base": "4px",
        "xs": "4px",
        "margin": "40px",
        "md": "16px"
      },
      "fontFamily": {
        "h2": ["Inter"],
        "body-md": ["Inter"],
        "h1": ["Inter"],
        "body-lg": ["Inter"],
        "numeric-display": ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "h3": ["Inter"]
      },
      "fontSize": {
        "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
        "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "400"}],
        "numeric-display": ["28px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h3": ["20px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};